import type { Order } from "./types"

export const data: Order[] = [
    {
        id: "CM9801",
        user: {
            name: "Natali Craig",
            avatar: "https://i.pravatar.cc/150?u=natali",
        },
        project: "Landing Page",
        address: "Meadow Lane Oakland",
        date: "Just now",
        status: "in-progress",
    },
    {
        id: "CM9802",
        user: {
            name: "Kate Morrison",
            avatar: "https://i.pravatar.cc/150?u=kate",
        },
        project: "CRM Admin pages",
        address: "Larry San Francisco",
        date: "A minute ago",
        status: "complete",
    },
    {
        id: "CM9803",
        user: {
            name: "Drew Cano",
            avatar: "https://i.pravatar.cc/150?u=drew",
        },
        project: "Client Project",
        address: "Bagwell Avenue Ocala",
        date: "1 hour ago",
        status: "pending",
    },
    {
        id: "CM9804",
        user: {
            name: "Orlando Diggs",
            avatar: "https://i.pravatar.cc/150?u=orlando",
        },
        project: "Admin Dashboard",
        address: "Washburn Baton Rouge",
        date: "Yesterday",
        status: "approved",
    },
    {
        id: "CM9805",
        user: {
            name: "Andi Lane",
            avatar: "https://i.pravatar.cc/150?u=andi",
        },
        project: "App Landing Page",
        address: "Nest Lane Olivette",
        date: "Feb 2, 2023",
        status: "rejected",
    },
    {
        id: "CM9806",
        user: {
            name: "Natali Craig",
            avatar: "https://i.pravatar.cc/150?u=natali2",
        },
        project: "Landing Page",
        address: "Meadow Lane Oakland",
        date: "Just now",
        status: "in-progress",
    },
    {
        id: "CM9807",
        user: {
            name: "Kate Morrison",
            avatar: "https://i.pravatar.cc/150?u=kate2",
        },
        project: "CRM Admin pages",
        address: "Larry San Francisco",
        date: "A minute ago",
        status: "complete",
    },
    {
        id: "CM9808",
        user: {
            name: "Drew Cano",
            avatar: "https://i.pravatar.cc/150?u=drew2",
        },
        project: "Client Project",
        address: "Bagwell Avenue Ocala",
        date: "1 hour ago",
        status: "pending",
    },
    {
        id: "CM9809",
        user: {
            name: "Orlando Diggs",
            avatar: "https://i.pravatar.cc/150?u=orlando2",
        },
        project: "Admin Dashboard",
        address: "Washburn Baton Rouge",
        date: "Yesterday",
        status: "approved",
    },
    {
        id: "CM9810",
        user: {
            name: "Andi Lane",
            avatar: "https://i.pravatar.cc/150?u=andi2",
        },
        project: "App Landing Page",
        address: "Nest Lane Olivette",
        date: "Feb 2, 2023",
        status: "rejected",
    },
    {
        id: "CM9811",
        user: {
            name: "Natali Craig",
            avatar: "https://i.pravatar.cc/150?u=natali3",
        },
        project: "Landing Page",
        address: "Meadow Lane Oakland",
        date: "Feb 1, 2023",
        status: "in-progress",
    },
    {
        id: "CM9812",
        user: {
            name: "Kate Morrison",
            avatar: "https://i.pravatar.cc/150?u=kate3",
        },
        project: "CRM Admin pages",
        address: "Larry San Francisco",
        date: "Jan 30, 2023",
        status: "complete",
    },
    {
        id: "CM9813",
        user: {
            name: "Drew Cano",
            avatar: "https://i.pravatar.cc/150?u=drew3",
        },
        project: "Client Project",
        address: "Bagwell Avenue Ocala",
        date: "Jan 28, 2023",
        status: "pending",
    },
    {
        id: "CM9814",
        user: {
            name: "Orlando Diggs",
            avatar: "https://i.pravatar.cc/150?u=orlando3",
        },
        project: "Admin Dashboard",
        address: "Washburn Baton Rouge",
        date: "Jan 25, 2023",
        status: "approved",
    },
    {
        id: "CM9815",
        user: {
            name: "Andi Lane",
            avatar: "https://i.pravatar.cc/150?u=andi3",
        },
        project: "App Landing Page",
        address: "Nest Lane Olivette",
        date: "Jan 22, 2023",
        status: "rejected",
    },
    {
        id: "CM9816",
        user: {
            name: "Natali Craig",
            avatar: "https://i.pravatar.cc/150?u=natali4",
        },
        project: "Landing Page",
        address: "Meadow Lane Oakland",
        date: "Jan 20, 2023",
        status: "in-progress",
    },
    {
        id: "CM9817",
        user: {
            name: "Kate Morrison",
            avatar: "https://i.pravatar.cc/150?u=kate4",
        },
        project: "CRM Admin pages",
        address: "Larry San Francisco",
        date: "Jan 18, 2023",
        status: "complete",
    },
    {
        id: "CM9818",
        user: {
            name: "Drew Cano",
            avatar: "https://i.pravatar.cc/150?u=drew4",
        },
        project: "Client Project",
        address: "Bagwell Avenue Ocala",
        date: "Jan 15, 2023",
        status: "pending",
    },
    {
        id: "CM9819",
        user: {
            name: "Orlando Diggs",
            avatar: "https://i.pravatar.cc/150?u=orlando4",
        },
        project: "Admin Dashboard",
        address: "Washburn Baton Rouge",
        date: "Jan 12, 2023",
        status: "approved",
    },
    {
        id: "CM9820",
        user: {
            name: "Andi Lane",
            avatar: "https://i.pravatar.cc/150?u=andi4",
        },
        project: "App Landing Page",
        address: "Nest Lane Olivette",
        date: "Jan 10, 2023",
        status: "rejected",
    },
    {
        id: "CM9821",
        user: {
            name: "Natali Craig",
            avatar: "https://i.pravatar.cc/150?u=natali5",
        },
        project: "Landing Page",
        address: "Meadow Lane Oakland",
        date: "Jan 8, 2023",
        status: "in-progress",
    },
    {
        id: "CM9822",
        user: {
            name: "Kate Morrison",
            avatar: "https://i.pravatar.cc/150?u=kate5",
        },
        project: "CRM Admin pages",
        address: "Larry San Francisco",
        date: "Jan 5, 2023",
        status: "complete",
    },
    {
        id: "CM9823",
        user: {
            name: "Drew Cano",
            avatar: "https://i.pravatar.cc/150?u=drew5",
        },
        project: "Client Project",
        address: "Bagwell Avenue Ocala",
        date: "Jan 3, 2023",
        status: "pending",
    },
    {
        id: "CM9824",
        user: {
            name: "Orlando Diggs",
            avatar: "https://i.pravatar.cc/150?u=orlando5",
        },
        project: "Admin Dashboard",
        address: "Washburn Baton Rouge",
        date: "Jan 1, 2023",
        status: "approved",
    },
    {
        id: "CM9825",
        user: {
            name: "Andi Lane",
            avatar: "https://i.pravatar.cc/150?u=andi5",
        },
        project: "App Landing Page",
        address: "Nest Lane Olivette",
        date: "Dec 30, 2022",
        status: "rejected",
    },
    {
        id: "CM9826",
        user: {
            name: "Natali Craig",
            avatar: "https://i.pravatar.cc/150?u=natali6",
        },
        project: "Landing Page",
        address: "Meadow Lane Oakland",
        date: "Dec 28, 2022",
        status: "in-progress",
    },
    {
        id: "CM9827",
        user: {
            name: "Kate Morrison",
            avatar: "https://i.pravatar.cc/150?u=kate6",
        },
        project: "CRM Admin pages",
        address: "Larry San Francisco",
        date: "Dec 25, 2022",
        status: "complete",
    },
    {
        id: "CM9828",
        user: {
            name: "Drew Cano",
            avatar: "https://i.pravatar.cc/150?u=drew6",
        },
        project: "Client Project",
        address: "Bagwell Avenue Ocala",
        date: "Dec 22, 2022",
        status: "pending",
    },
    {
        id: "CM9829",
        user: {
            name: "Orlando Diggs",
            avatar: "https://i.pravatar.cc/150?u=orlando6",
        },
        project: "Admin Dashboard",
        address: "Washburn Baton Rouge",
        date: "Dec 20, 2022",
        status: "approved",
    },
    {
        id: "CM9830",
        user: {
            name: "Andi Lane",
            avatar: "https://i.pravatar.cc/150?u=andi6",
        },
        project: "App Landing Page",
        address: "Nest Lane Olivette",
        date: "Dec 18, 2022",
        status: "rejected",
    },
    {
        id: "CM9831",
        user: {
            name: "Natali Craig",
            avatar: "https://i.pravatar.cc/150?u=natali7",
        },
        project: "Landing Page",
        address: "Meadow Lane Oakland",
        date: "Dec 15, 2022",
        status: "in-progress",
    },
    {
        id: "CM9832",
        user: {
            name: "Kate Morrison",
            avatar: "https://i.pravatar.cc/150?u=kate7",
        },
        project: "CRM Admin pages",
        address: "Larry San Francisco",
        date: "Dec 12, 2022",
        status: "complete",
    },
    {
        id: "CM9833",
        user: {
            name: "Drew Cano",
            avatar: "https://i.pravatar.cc/150?u=drew7",
        },
        project: "Client Project",
        address: "Bagwell Avenue Ocala",
        date: "Dec 10, 2022",
        status: "pending",
    },
    {
        id: "CM9834",
        user: {
            name: "Orlando Diggs",
            avatar: "https://i.pravatar.cc/150?u=orlando7",
        },
        project: "Admin Dashboard",
        address: "Washburn Baton Rouge",
        date: "Dec 8, 2022",
        status: "approved",
    },
    {
        id: "CM9835",
        user: {
            name: "Andi Lane",
            avatar: "https://i.pravatar.cc/150?u=andi7",
        },
        project: "App Landing Page",
        address: "Nest Lane Olivette",
        date: "Dec 5, 2022",
        status: "rejected",
    },
    {
        id: "CM9836",
        user: {
            name: "Natali Craig",
            avatar: "https://i.pravatar.cc/150?u=natali8",
        },
        project: "Landing Page",
        address: "Meadow Lane Oakland",
        date: "Dec 3, 2022",
        status: "in-progress",
    },
    {
        id: "CM9837",
        user: {
            name: "Kate Morrison",
            avatar: "https://i.pravatar.cc/150?u=kate8",
        },
        project: "CRM Admin pages",
        address: "Larry San Francisco",
        date: "Dec 1, 2022",
        status: "complete",
    },
    {
        id: "CM9838",
        user: {
            name: "Drew Cano",
            avatar: "https://i.pravatar.cc/150?u=drew8",
        },
        project: "Client Project",
        address: "Bagwell Avenue Ocala",
        date: "Nov 28, 2022",
        status: "pending",
    },
    {
        id: "CM9839",
        user: {
            name: "Orlando Diggs",
            avatar: "https://i.pravatar.cc/150?u=orlando8",
        },
        project: "Admin Dashboard",
        address: "Washburn Baton Rouge",
        date: "Nov 25, 2022",
        status: "approved",
    },
    {
        id: "CM9840",
        user: {
            name: "Andi Lane",
            avatar: "https://i.pravatar.cc/150?u=andi8",
        },
        project: "App Landing Page",
        address: "Nest Lane Olivette",
        date: "Nov 22, 2022",
        status: "rejected",
    },
    {
        id: "CM9841",
        user: {
            name: "Natali Craig",
            avatar: "https://i.pravatar.cc/150?u=natali9",
        },
        project: "Landing Page",
        address: "Meadow Lane Oakland",
        date: "Nov 20, 2022",
        status: "in-progress",
    },
    {
        id: "CM9842",
        user: {
            name: "Kate Morrison",
            avatar: "https://i.pravatar.cc/150?u=kate9",
        },
        project: "CRM Admin pages",
        address: "Larry San Francisco",
        date: "Nov 18, 2022",
        status: "complete",
    },
    {
        id: "CM9843",
        user: {
            name: "Drew Cano",
            avatar: "https://i.pravatar.cc/150?u=drew9",
        },
        project: "Client Project",
        address: "Bagwell Avenue Ocala",
        date: "Nov 15, 2022",
        status: "pending",
    },
    {
        id: "CM9844",
        user: {
            name: "Orlando Diggs",
            avatar: "https://i.pravatar.cc/150?u=orlando9",
        },
        project: "Admin Dashboard",
        address: "Washburn Baton Rouge",
        date: "Nov 12, 2022",
        status: "approved",
    },
    {
        id: "CM9845",
        user: {
            name: "Andi Lane",
            avatar: "https://i.pravatar.cc/150?u=andi9",
        },
        project: "App Landing Page",
        address: "Nest Lane Olivette",
        date: "Nov 10, 2022",
        status: "rejected",
    },
    {
        id: "CM9846",
        user: {
            name: "Natali Craig",
            avatar: "https://i.pravatar.cc/150?u=natali10",
        },
        project: "Landing Page",
        address: "Meadow Lane Oakland",
        date: "Nov 8, 2022",
        status: "in-progress",
    },
    {
        id: "CM9847",
        user: {
            name: "Kate Morrison",
            avatar: "https://i.pravatar.cc/150?u=kate10",
        },
        project: "CRM Admin pages",
        address: "Larry San Francisco",
        date: "Nov 5, 2022",
        status: "complete",
    },
    {
        id: "CM9848",
        user: {
            name: "Drew Cano",
            avatar: "https://i.pravatar.cc/150?u=drew10",
        },
        project: "Client Project",
        address: "Bagwell Avenue Ocala",
        date: "Nov 3, 2022",
        status: "pending",
    },
    {
        id: "CM9849",
        user: {
            name: "Orlando Diggs",
            avatar: "https://i.pravatar.cc/150?u=orlando10",
        },
        project: "Admin Dashboard",
        address: "Washburn Baton Rouge",
        date: "Nov 1, 2022",
        status: "approved",
    },
    {
        id: "CM9850",
        user: {
            name: "Andi Lane",
            avatar: "https://i.pravatar.cc/150?u=andi10",
        },
        project: "App Landing Page",
        address: "Nest Lane Olivette",
        date: "Oct 30, 2022",
        status: "rejected",
    },
]

export const statusConfig = {
    "in-progress": { label: "In Progress", color: "bg-[#95a4fc]", textColor: "text-[#8b8cd9]" },
    "complete": { label: "Complete", color: "bg-[#a1e3cb]", textColor: "text-[#4aa785]" },
    "pending": { label: "Pending", color: "bg-[#b0e3ff]", textColor: "text-[#59a8d4]" },
    "approved": { label: "Approved", color: "bg-[#ffe999]", textColor: "text-[#ffc655]" },
    "rejected": { label: "Rejected", color: "bg-[#a0a1a2]", textColor: "text-[#a4a4a4]" },
}

